- depth: 2
  hidden_layer_width: 32
  learning_rate: 0.001
  optimizer: SGD
- depth: 2
  hidden_layer_width: 32
  learning_rate: 0.001
  optimizer: Adam
- depth: 2
  hidden_layer_width: 32
  learning_rate: 0.01
  optimizer: SGD
- depth: 2
  hidden_layer_width: 32
  learning_rate: 0.01
  optimizer: Adam
- depth: 2
  hidden_layer_width: 32
  learning_rate: 0.1
  optimizer: SGD
- depth: 2
  hidden_layer_width: 32
  learning_rate: 0.1
  optimizer: Adam
